/*
 * This header is a configuration header profile for a fast header only library variant.
 *
 * @TODO: should be generated by cmake later
 */
#define OHA_INLINE_ALL
#define OHA_DISABLE_NULL_POINTER_CHECKS
#define OHA_CALLOC_LPHT_VALUE_AT_INIT
#include "oha.h"
